# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab1/lab1.srcs/sources_1/ip/mr_bram/mr_bram.xci
# IP: The module: 'mr_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab1/lab1.srcs/sources_1/ip/mr_bram/mr_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mr_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab1/lab1.srcs/sources_1/ip/mr_bram/mr_bram.xci
# IP: The module: 'mr_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab1/lab1.srcs/sources_1/ip/mr_bram/mr_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mr_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
