# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.cache/wt [current_project]
set_property parent.project_path D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/ComputerScience/hitcs/hitcs/lcd_controller/lcd_controller.srcs/sources_1
  d:/ComputerScience/hitcs/hitcs/ma_river_core/ma_river_core.srcs/sources_1
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/lcd_controller_0/ip/rst_rom.coe
add_files D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/lcd_controller_0/ip/font_rom.coe
add_files D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/imports/coding/hitcoa_at2024/cache_trace.coe
add_files D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/imports/coding/hitcoa_at/cache/lab_4/axi_ram.coe
add_files D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/imports/hitcoa_at2024/cache_checker.coe
read_verilog -library xil_defaultlib {
  D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/imports/labs/cache.v
  D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/new/cache_checker.v
  D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/imports/new/checker_wrapper.v
  D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/new/soc_top.v
}
read_ip -quiet D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/axi_bus/axi_bus.xci
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/axi_bus/axi_bus_ooc.xdc]

read_ip -quiet D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/ma_river_core_0/ma_river_core_0.xci
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/ma_river_core_0/ip/bram_sd/bram_sd_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/ma_river_core_0/ip/bram_td/bram_td_ooc.xdc]

read_ip -quiet D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/lcd_controller_0/lcd_controller_0.xci
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/lcd_controller_0/ip/font_rom/font_rom_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/lcd_controller_0/ip/rst_rom/rst_rom_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/lcd_controller_0/ip/text_bram/text_bram_ooc.xdc]

read_ip -quiet D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/mr_bram/mr_bram.xci
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/mr_bram/mr_bram_ooc.xdc]

read_ip -quiet D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/clk_pll/clk_pll_ooc.xdc]

read_ip -quiet D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/axi/axi.xci
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/axi/axi_ooc.xdc]

read_ip -quiet D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/cache_trace/cache_trace.xci
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/cache_trace/cache_trace_ooc.xdc]

read_ip -quiet D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/constrs_1/imports/new/cons.xdc
set_property used_in_implementation false [get_files D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab3/lab3.srcs/constrs_1/imports/new/cons.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_top -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_top_utilization_synth.rpt -pb soc_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
