# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/computer science/project_4/project_4.srcs/sources_1/ip/ans_ram/ans_ram.xci
# IP: The module: 'ans_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/computer science/project_4/project_4.srcs/sources_1/ip/ans_ram/ans_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ans_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/computer science/project_4/project_4.srcs/sources_1/ip/ans_ram/ans_ram.xci
# IP: The module: 'ans_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/computer science/project_4/project_4.srcs/sources_1/ip/ans_ram/ans_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ans_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
