set_property PACKAGE_PIN AC19 [get_ports sys_clk]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets sys_clk]
create_clock -period 10.000 -name sys_clk -waveform {0.000 5.000} [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]


set_property PACKAGE_PIN Y3 [get_ports sys_rstn]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rstn]

set_property PACKAGE_PIN H9 [get_ports {lcd_db[0]}]
set_property PACKAGE_PIN K17 [get_ports {lcd_db[1]}]
set_property PACKAGE_PIN J20 [get_ports {lcd_db[2]}]
set_property PACKAGE_PIN M17 [get_ports {lcd_db[3]}]
set_property PACKAGE_PIN L17 [get_ports {lcd_db[4]}]
set_property PACKAGE_PIN L18 [get_ports {lcd_db[5]}]
set_property PACKAGE_PIN L15 [get_ports {lcd_db[6]}]
set_property PACKAGE_PIN M15 [get_ports {lcd_db[7]}]
set_property PACKAGE_PIN M16 [get_ports {lcd_db[8]}]
set_property PACKAGE_PIN L14 [get_ports {lcd_db[9]}]
set_property PACKAGE_PIN M14 [get_ports {lcd_db[10]}]
set_property PACKAGE_PIN F22 [get_ports {lcd_db[11]}]
set_property PACKAGE_PIN G22 [get_ports {lcd_db[12]}]
set_property PACKAGE_PIN G21 [get_ports {lcd_db[13]}]
set_property PACKAGE_PIN H24 [get_ports {lcd_db[14]}]
set_property PACKAGE_PIN J16 [get_ports {lcd_db[15]}]

set_property PACKAGE_PIN J25 [get_ports lcd_rst]
set_property PACKAGE_PIN H18 [get_ports lcd_cs]
set_property PACKAGE_PIN K16 [get_ports lcd_rs]
set_property PACKAGE_PIN L8 [get_ports lcd_wr]
set_property PACKAGE_PIN K8 [get_ports lcd_rd]
set_property PACKAGE_PIN J15 [get_ports lcd_bl_ctr]

set_property IOSTANDARD LVCMOS33 [get_ports lcd_rst]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_cs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rd]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_wr]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_db[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_bl_ctr]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list pll/inst/clk_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 5 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {your_cpu/debug_wb_rf_wnum[0]} {your_cpu/debug_wb_rf_wnum[1]} {your_cpu/debug_wb_rf_wnum[2]} {your_cpu/debug_wb_rf_wnum[3]} {your_cpu/debug_wb_rf_wnum[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {your_cpu/debug_wb_rf_wdata[0]} {your_cpu/debug_wb_rf_wdata[1]} {your_cpu/debug_wb_rf_wdata[2]} {your_cpu/debug_wb_rf_wdata[3]} {your_cpu/debug_wb_rf_wdata[4]} {your_cpu/debug_wb_rf_wdata[5]} {your_cpu/debug_wb_rf_wdata[6]} {your_cpu/debug_wb_rf_wdata[7]} {your_cpu/debug_wb_rf_wdata[8]} {your_cpu/debug_wb_rf_wdata[9]} {your_cpu/debug_wb_rf_wdata[10]} {your_cpu/debug_wb_rf_wdata[11]} {your_cpu/debug_wb_rf_wdata[12]} {your_cpu/debug_wb_rf_wdata[13]} {your_cpu/debug_wb_rf_wdata[14]} {your_cpu/debug_wb_rf_wdata[15]} {your_cpu/debug_wb_rf_wdata[16]} {your_cpu/debug_wb_rf_wdata[17]} {your_cpu/debug_wb_rf_wdata[18]} {your_cpu/debug_wb_rf_wdata[19]} {your_cpu/debug_wb_rf_wdata[20]} {your_cpu/debug_wb_rf_wdata[21]} {your_cpu/debug_wb_rf_wdata[22]} {your_cpu/debug_wb_rf_wdata[23]} {your_cpu/debug_wb_rf_wdata[24]} {your_cpu/debug_wb_rf_wdata[25]} {your_cpu/debug_wb_rf_wdata[26]} {your_cpu/debug_wb_rf_wdata[27]} {your_cpu/debug_wb_rf_wdata[28]} {your_cpu/debug_wb_rf_wdata[29]} {your_cpu/debug_wb_rf_wdata[30]} {your_cpu/debug_wb_rf_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {your_cpu/IR[0]} {your_cpu/IR[1]} {your_cpu/IR[2]} {your_cpu/IR[3]} {your_cpu/IR[4]} {your_cpu/IR[5]} {your_cpu/IR[6]} {your_cpu/IR[7]} {your_cpu/IR[8]} {your_cpu/IR[9]} {your_cpu/IR[10]} {your_cpu/IR[11]} {your_cpu/IR[12]} {your_cpu/IR[13]} {your_cpu/IR[14]} {your_cpu/IR[15]} {your_cpu/IR[16]} {your_cpu/IR[17]} {your_cpu/IR[18]} {your_cpu/IR[19]} {your_cpu/IR[20]} {your_cpu/IR[21]} {your_cpu/IR[22]} {your_cpu/IR[23]} {your_cpu/IR[24]} {your_cpu/IR[25]} {your_cpu/IR[26]} {your_cpu/IR[27]} {your_cpu/IR[28]} {your_cpu/IR[29]} {your_cpu/IR[30]} {your_cpu/IR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {your_cpu/PC[0]} {your_cpu/PC[1]} {your_cpu/PC[2]} {your_cpu/PC[3]} {your_cpu/PC[4]} {your_cpu/PC[5]} {your_cpu/PC[6]} {your_cpu/PC[7]} {your_cpu/PC[8]} {your_cpu/PC[9]} {your_cpu/PC[10]} {your_cpu/PC[11]} {your_cpu/PC[12]} {your_cpu/PC[13]} {your_cpu/PC[14]} {your_cpu/PC[15]} {your_cpu/PC[16]} {your_cpu/PC[17]} {your_cpu/PC[18]} {your_cpu/PC[19]} {your_cpu/PC[20]} {your_cpu/PC[21]} {your_cpu/PC[22]} {your_cpu/PC[23]} {your_cpu/PC[24]} {your_cpu/PC[25]} {your_cpu/PC[26]} {your_cpu/PC[27]} {your_cpu/PC[28]} {your_cpu/PC[29]} {your_cpu/PC[30]} {your_cpu/PC[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list your_cpu/debug_wb_rf_wen]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk50]
