# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/coa/lab2/lab2.srcs/sources_1/ip/cpu_ans0_rom_1/cpu_ans0_rom.xci
# IP: The module: 'cpu_ans0_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/coa/lab2/lab2.srcs/sources_1/ip/cpu_ans0_rom_1/cpu_ans0_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_ans0_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/coa/lab2/lab2.srcs/sources_1/ip/cpu_ans0_rom_1/cpu_ans0_rom.xci
# IP: The module: 'cpu_ans0_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/coa/lab2/lab2.srcs/sources_1/ip/cpu_ans0_rom_1/cpu_ans0_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_ans0_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
