set_property SRC_FILE_INFO {cfile:D:/ComputerScience/CPU_design/lab5/lab5/lab5/lab5.srcs/constrs_1/imports/new/cons.xdc rfile:../../../lab5.srcs/constrs_1/imports/new/cons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC19 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y3 [get_ports sys_rstn]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H9 [get_ports {lcd_db[0]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports {lcd_db[1]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports {lcd_db[2]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports {lcd_db[3]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports {lcd_db[4]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18 [get_ports {lcd_db[5]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {lcd_db[6]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {lcd_db[7]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports {lcd_db[8]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {lcd_db[9]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {lcd_db[10]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports {lcd_db[11]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports {lcd_db[12]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G21 [get_ports {lcd_db[13]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H24 [get_ports {lcd_db[14]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports {lcd_db[15]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J25 [get_ports lcd_rst]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports lcd_cs]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports lcd_rs]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L8 [get_ports lcd_wr]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K8 [get_ports lcd_rd]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports lcd_bl_ctr]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list pll/inst/clk_out]]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {your_cpu/debug_wb_rf_wdata[0]} {your_cpu/debug_wb_rf_wdata[1]} {your_cpu/debug_wb_rf_wdata[2]} {your_cpu/debug_wb_rf_wdata[3]} {your_cpu/debug_wb_rf_wdata[4]} {your_cpu/debug_wb_rf_wdata[5]} {your_cpu/debug_wb_rf_wdata[6]} {your_cpu/debug_wb_rf_wdata[7]} {your_cpu/debug_wb_rf_wdata[8]} {your_cpu/debug_wb_rf_wdata[9]} {your_cpu/debug_wb_rf_wdata[10]} {your_cpu/debug_wb_rf_wdata[11]} {your_cpu/debug_wb_rf_wdata[12]} {your_cpu/debug_wb_rf_wdata[13]} {your_cpu/debug_wb_rf_wdata[14]} {your_cpu/debug_wb_rf_wdata[15]} {your_cpu/debug_wb_rf_wdata[16]} {your_cpu/debug_wb_rf_wdata[17]} {your_cpu/debug_wb_rf_wdata[18]} {your_cpu/debug_wb_rf_wdata[19]} {your_cpu/debug_wb_rf_wdata[20]} {your_cpu/debug_wb_rf_wdata[21]} {your_cpu/debug_wb_rf_wdata[22]} {your_cpu/debug_wb_rf_wdata[23]} {your_cpu/debug_wb_rf_wdata[24]} {your_cpu/debug_wb_rf_wdata[25]} {your_cpu/debug_wb_rf_wdata[26]} {your_cpu/debug_wb_rf_wdata[27]} {your_cpu/debug_wb_rf_wdata[28]} {your_cpu/debug_wb_rf_wdata[29]} {your_cpu/debug_wb_rf_wdata[30]} {your_cpu/debug_wb_rf_wdata[31]}]]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {your_cpu/PC[0]} {your_cpu/PC[1]} {your_cpu/PC[2]} {your_cpu/PC[3]} {your_cpu/PC[4]} {your_cpu/PC[5]} {your_cpu/PC[6]} {your_cpu/PC[7]} {your_cpu/PC[8]} {your_cpu/PC[9]} {your_cpu/PC[10]} {your_cpu/PC[11]} {your_cpu/PC[12]} {your_cpu/PC[13]} {your_cpu/PC[14]} {your_cpu/PC[15]} {your_cpu/PC[16]} {your_cpu/PC[17]} {your_cpu/PC[18]} {your_cpu/PC[19]} {your_cpu/PC[20]} {your_cpu/PC[21]} {your_cpu/PC[22]} {your_cpu/PC[23]} {your_cpu/PC[24]} {your_cpu/PC[25]} {your_cpu/PC[26]} {your_cpu/PC[27]} {your_cpu/PC[28]} {your_cpu/PC[29]} {your_cpu/PC[30]} {your_cpu/PC[31]}]]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {your_cpu/debug_wb_rf_wnum[0]} {your_cpu/debug_wb_rf_wnum[1]} {your_cpu/debug_wb_rf_wnum[2]} {your_cpu/debug_wb_rf_wnum[3]} {your_cpu/debug_wb_rf_wnum[4]}]]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {your_cpu/IR[0]} {your_cpu/IR[1]} {your_cpu/IR[2]} {your_cpu/IR[3]} {your_cpu/IR[4]} {your_cpu/IR[5]} {your_cpu/IR[6]} {your_cpu/IR[7]} {your_cpu/IR[8]} {your_cpu/IR[9]} {your_cpu/IR[10]} {your_cpu/IR[11]} {your_cpu/IR[12]} {your_cpu/IR[13]} {your_cpu/IR[14]} {your_cpu/IR[15]} {your_cpu/IR[16]} {your_cpu/IR[17]} {your_cpu/IR[18]} {your_cpu/IR[19]} {your_cpu/IR[20]} {your_cpu/IR[21]} {your_cpu/IR[22]} {your_cpu/IR[23]} {your_cpu/IR[24]} {your_cpu/IR[25]} {your_cpu/IR[26]} {your_cpu/IR[27]} {your_cpu/IR[28]} {your_cpu/IR[29]} {your_cpu/IR[30]} {your_cpu/IR[31]}]]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list your_cpu/debug_wb_rf_wen]]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk50]
