# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab1/lab1.srcs/sources_1/ip/cpu_inst2_rom/cpu_inst2_rom.xci
# IP: The module: 'cpu_inst2_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab1/lab1.srcs/sources_1/ip/cpu_inst2_rom/cpu_inst2_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_inst2_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab1/lab1.srcs/sources_1/ip/cpu_inst2_rom/cpu_inst2_rom.xci
# IP: The module: 'cpu_inst2_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ComputerScience/hitcs/hitcs/computer_architecture/labs/lab1/lab1.srcs/sources_1/ip/cpu_inst2_rom/cpu_inst2_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_inst2_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
