# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ywy_c/Documents/coding/hitcoa_at2024/coa/release/lab3/lab3.srcs/sources_1/ip/cache_trace/cache_trace.xci
# IP: The module: 'cache_trace' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/coa/release/lab3/lab3.srcs/sources_1/ip/cache_trace/cache_trace_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cache_trace'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/ywy_c/Documents/coding/hitcoa_at2024/coa/release/lab3/lab3.srcs/sources_1/ip/cache_trace/cache_trace.xci
# IP: The module: 'cache_trace' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ywy_c/Documents/coding/hitcoa_at2024/coa/release/lab3/lab3.srcs/sources_1/ip/cache_trace/cache_trace_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cache_trace'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
